name: My First Workflow

on:
  push:
  workflow_dispatch:

jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # multi line commands 
      - name: Welcome message
        run: |
          echo "My first github actions workflow"
          ls -ltra
          cat README.md
          python first.py


      # - name: List files
      #   run: ls

      # - name: Read file
      #   run: cat README.md

      # - name: Run python file
      #   run: python first.py


      # generate ASCII code
  second_job:
    runs-on: ubuntu-latest
    steps:
      # we are running these commands using shell script 
      # - name: Install cowsay program
      #   run: sudo apt-get install cowsay -y 

      # - name: Run cowsay command
      #   run: cowsay -f dragon "run for cover, I AM DRAGON...RRR" >> dragon.txt

      # - name: Read dragon file
      #   run: cat dragon.txt

      - name: Executing shell script
        run: ./ascii-script.sh



